name: Java CI with Maven

on:
  push:
    paths:
      - '**/**'  # 监控所有文件的更改
  pull_request:
    paths:
      - '**/**'  # 监控所有文件的更改

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.372+7'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Archive JAR file
      uses: actions/upload-artifact@v3
      with:
        name: MineBBSTopper
        path: target/MineBBSTopper-*.jar
